name: tdd_clean_architecture
description: TDD Clean Architecture Number Trivia App.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Functional Programming
  dartz: ^0.10.1
  # Value Equality
  equatable: ^2.0.5
  # State Management
  flutter_bloc: ^8.1.3
  # Service Locator
  get_it: ^7.6.0
  # Local Storage
  shared_preferences: ^2.1.2
  # Remote API
  internet_connection_checker: ^1.0.0+1
  http: ^0.13.6

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
flutter:
  uses-material-design: true
